
version: '3'


services:

  webapp:
    build:
      context: .
      dockerfile: 'Dockerfile'
    image: flask-vue
    container_name: flask-vue
    restart: always
    links:
      - mysql:mysql
      - redis:redis
    ports:
     - "80:80"
    volumes:
     - /app/client/node_modules
    command: /usr/bin/supervisord

  mysql:
    image: mysql:5.7
    container_name: flask-vue-mysql
    restart: always
    volumes:
     - ./mysql_store:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=test

  adminer:
    image: adminer:4.6.2
    container_name: flask-vue-adminer
    restart: always
    links:
      - mysql:mysql
    ports:
      - "8080:8080"

  redis:
    image: redis:4.0.9-alpine
    container_name: flask-vue-redis
    restart: always
    volumes:
     - ./redis_store:/data

